import { createMiniUnit, createUnit, choiceQuestion, shortQuestion } from "./helpers.js";

const proportionalQuestions = [
  choiceQuestion({
    prompt: "y가 x에 정비례할 때 알맞은 식은?",
    options: ["y = x + 3", "y = 3x", "y = 3/x", "xy = 3x"],
    answer: 1,
    explanation: "정비례는 y = ax 꼴로 나타낸다.",
    wrongReasons: [
      "상수항이 있으면 정비례가 아니다.",
      "3/x는 반비례 식이다.",
      "식 형태가 정비례 기본형이 아니다.",
    ],
    difficulty: "쉬움",
    category: "개념 확인",
    relatedConcept: "정비례",
  }),
  choiceQuestion({
    prompt: "x가 2배가 될 때 y가 1/2배가 되면 두 양의 관계는?",
    options: ["정비례", "반비례", "일차함수", "비례 관계가 아님"],
    answer: 1,
    explanation: "한 양이 커질 때 다른 양이 그에 반대로 줄어 곱이 일정하면 반비례이다.",
    wrongReasons: [
      "정비례는 같은 방향으로 변한다.",
      "반비례는 일차함수 그래프와 다르다.",
      "주어진 정보로 반비례 판단이 가능하다.",
    ],
    difficulty: "보통",
    category: "개념 확인",
    relatedConcept: "반비례",
  }),
  choiceQuestion({
    prompt: "정비례 그래프가 반드시 지나는 점은?",
    options: ["(1, 1)", "(0, 0)", "(1, 0)", "(0, 1)"],
    answer: 1,
    explanation: "정비례식 y=ax에서 x=0이면 y=0이므로 원점을 지난다.",
    wrongReasons: [
      "비례상수에 따라 달라지는 점이다.",
      "원점이 아닌 다른 축 위 점을 항상 지나지 않는다.",
      "정비례의 핵심 특징은 원점 통과이다.",
    ],
    difficulty: "보통",
    category: "개념 확인",
    relatedConcept: "정비례 그래프",
  }),
  choiceQuestion({
    prompt: "반비례식 y = 12/x에서 x=3일 때 y는?",
    options: ["4", "6", "9", "36"],
    answer: 0,
    explanation: "y = 12/3 = 4이다.",
    wrongReasons: [
      "대입 계산을 정확히 해야 한다.",
      "곱을 잘못 처리한 값이다.",
      "제곱처럼 계산한 오답이다.",
    ],
    difficulty: "쉬움",
    category: "개념 확인",
    relatedConcept: "반비례식",
  }),
  choiceQuestion({
    prompt: "정비례에서 비례상수 a의 의미로 가장 알맞은 것은?",
    options: ["x와 y의 합", "x가 1 증가할 때 y의 변화량", "x가 1일 때의 y값", "항상 음수인 값"],
    answer: 2,
    explanation: "y=ax에서 x=1이면 y=a이므로 비례상수는 x가 1일 때 y값으로 볼 수 있다.",
    wrongReasons: [
      "합을 의미하지 않는다.",
      "정비례에서도 변화량 관점이 가능하지만 가장 직접적인 정의는 x=1일 때 y값이다.",
      "비례상수는 양수일 수도 음수일 수도 있다.",
    ],
    difficulty: "보통",
    category: "개념 확인",
    relatedConcept: "비례상수",
  }),
  choiceQuestion({
    prompt: "다음 중 정비례 관계인 상황은?",
    options: [
      "거리와 걸린 시간이 항상 같은 비로 늘어나는 경우",
      "한 변의 길이와 정사각형 넓이",
      "물체 수와 한 개당 가격이 반대로 변하는 경우",
      "x가 커져도 y가 일정한 경우",
    ],
    answer: 0,
    explanation: "속력이 일정하면 거리와 시간은 정비례한다.",
    wrongReasons: [
      "넓이는 제곱 관계다.",
      "반대로 변하면 반비례 상황이다.",
      "상수 관계는 정비례가 아니다.",
    ],
    difficulty: "보통",
    category: "객관식",
    relatedConcept: "정비례",
  }),
  choiceQuestion({
    prompt: "반비례 그래프의 모양 설명으로 알맞은 것은?",
    options: [
      "원점을 지나는 직선",
      "x축과 평행한 직선",
      "축에 가까워지지만 만나지 않는 곡선 두 갈래",
      "포물선",
    ],
    answer: 2,
    explanation: "반비례 그래프는 쌍곡선 모양으로 좌표축에 가까워지지만 만나지 않는다.",
    wrongReasons: [
      "이는 정비례 그래프 특징이다.",
      "상수 함수의 그래프이다.",
      "이차함수의 그래프이다.",
    ],
    difficulty: "보통",
    category: "객관식",
    relatedConcept: "반비례 그래프",
  }),
  choiceQuestion({
    prompt: "정비례식 y = -2x의 그래프에 대한 설명으로 옳은 것은?",
    options: [
      "원점을 지나며 오른쪽 위로 올라간다.",
      "원점을 지나며 오른쪽 아래로 내려간다.",
      "y절편이 -2이다.",
      "x가 커질수록 y도 커진다.",
    ],
    answer: 1,
    explanation: "비례상수가 음수이면 원점을 지나면서 오른쪽 아래로 내려간다.",
    wrongReasons: [
      "양수 기울기와 반대이다.",
      "정비례는 y절편이 0이다.",
      "음수 비례상수이므로 y는 감소한다.",
    ],
    difficulty: "어려움",
    category: "객관식",
    relatedConcept: "정비례 그래프",
  }),
  choiceQuestion({
    prompt: "반비례 관계에서 x와 y의 곱은 어떻게 되는가?",
    options: ["항상 일정하다", "항상 0이다", "항상 증가한다", "항상 1이다"],
    answer: 0,
    explanation: "반비례식 y = a/x에서 xy = a이므로 곱이 일정하다.",
    wrongReasons: [
      "0이나 1로 정해져 있지 않다.",
      "증가 여부가 아니라 일정함이 핵심이다.",
      "비례상수는 여러 값이 될 수 있다.",
    ],
    difficulty: "쉬움",
    category: "객관식",
    relatedConcept: "반비례",
  }),
  choiceQuestion({
    prompt: "정비례와 반비례를 구분할 때 가장 먼저 보는 기준으로 알맞은 것은?",
    options: [
      "그래프 색깔",
      "한 양이 변할 때 다른 양이 같은 방향인지, 곱이나 비가 일정한지",
      "문제 길이",
      "숫자의 크기",
    ],
    answer: 1,
    explanation: "정비례는 비가 일정, 반비례는 곱이 일정하다는 점을 먼저 본다.",
    wrongReasons: [
      "색깔과 길이는 판단 기준이 아니다.",
      "숫자 크기만으로는 관계를 알 수 없다.",
      "관계의 성질을 봐야 한다.",
    ],
    difficulty: "보통",
    category: "객관식",
    relatedConcept: "정비례와 반비례 비교",
  }),
  shortQuestion({
    prompt: "정비례와 반비례의 차이를 비와 곱의 관점에서 설명하시오.",
    answer: "정비례는 두 양의 비가 일정하고, 반비례는 두 양의 곱이 일정하다.",
    explanation: "비와 곱을 각각 연결해야 한다.",
    difficulty: "어려움",
    category: "서술형",
    relatedConcept: "정비례와 반비례 비교",
  }),
  shortQuestion({
    prompt: "정비례 그래프가 원점을 지나는 이유를 식으로 설명하시오.",
    answer: "정비례식 y=ax에서 x=0이면 y=0이므로 원점을 지난다.",
    explanation: "식 대입이 포함되면 더 완전한 답이 된다.",
    difficulty: "어려움",
    category: "서술형",
    relatedConcept: "정비례 그래프",
  }),
  shortQuestion({
    prompt: "반비례 상황의 실생활 예를 하나 들고 왜 반비례인지 설명하시오.",
    answer: "일정한 거리를 갈 때 속력이 빠를수록 걸리는 시간은 짧아지므로 두 양의 곱이 일정한 반비례 상황이다.",
    explanation: "예시와 반비례 이유를 모두 써야 한다.",
    difficulty: "어려움",
    category: "서술형",
    relatedConcept: "반비례",
  }),
  shortQuestion({
    prompt: "표로 제시된 두 양이 정비례인지 반비례인지 판단하는 절차를 설명하시오.",
    answer: "대응하는 값들의 비가 일정한지 먼저 보고, 아니면 곱이 일정한지 확인한다.",
    explanation: "정비례-비, 반비례-곱 순서로 확인하면 좋다.",
    difficulty: "만점 도전",
    category: "심화",
    relatedConcept: "정비례와 반비례 비교",
  }),
  shortQuestion({
    prompt: "정비례 관계와 일차함수 관계가 비슷해 보여도 구별해야 하는 이유를 설명하시오.",
    answer: "정비례는 y=ax로 원점을 지나지만, 일차함수는 y=ax+b로 상수항이 있을 수 있어 원점을 지나지 않을 수 있다.",
    explanation: "원점 통과와 상수항 여부를 구분하면 만점형 답안이 된다.",
    difficulty: "만점 도전",
    category: "심화",
    relatedConcept: "정비례와 일차함수 비교",
  }),
];

const math = {
  id: "math",
  name: "수학",
  icon: "🧮",
  color: "#2d6cdf",
  description: "공식을 외우는 데서 멈추지 않고, 왜 그런 식이 나오는지와 그래프 해석까지 연결하는 과목입니다.",
  grades: [
    {
      id: "elementary4",
      name: "초등학교 4학년",
      units: [
        createMiniUnit({
          subject: "math",
          grade: "elementary4",
          title: "도형과 각도 기초",
          field: "도형",
          difficulty: "기초",
          teaser: "점, 선, 각과 직각, 예각, 둔각을 중학교 도형 학습의 바탕으로 정리합니다.",
          achievementGoals: [
            "기본 도형 요소와 각의 뜻을 설명할 수 있다.",
            "직각, 예각, 둔각을 구분할 수 있다.",
            "생활 속 도형과 각도를 찾아 말할 수 있다.",
          ],
          examImportance: "각도와 도형 용어를 정확히 잡아 두면 이후 평면도형과 작도 학습이 훨씬 쉬워진다.",
          concepts: [
            { term: "각", simple: "두 반직선이 만나 이루는 모양", detailed: "꼭짓점과 변으로 이루어지며 크기를 잴 수 있다.", exam: "꼭짓점과 변 개념을 함께 쓴다." },
            { term: "직각", simple: "90도인 각", detailed: "네모 모서리처럼 반듯한 각", exam: "기준 각도" },
            { term: "예각", simple: "90도보다 작은 각", detailed: "직각보다 좁은 각", exam: "직각과 비교해 판단" },
            { term: "둔각", simple: "90도보다 크고 180도보다 작은 각", detailed: "직각보다 넓은 각", exam: "평각과 구별" },
          ],
        }),
      ],
    },
    {
      id: "elementary6",
      name: "초등학교 6학년",
      units: [
        createMiniUnit({
          subject: "math",
          grade: "elementary6",
          title: "비와 비율",
          field: "수와 연산",
          difficulty: "기초",
          teaser: "비의 뜻과 비율 계산을 중학교 비례 개념의 준비 단계로 정리합니다.",
          achievementGoals: [
            "비와 비율의 뜻을 말할 수 있다.",
            "두 양의 관계를 비로 나타낼 수 있다.",
            "비율을 퍼센트와 연결할 수 있다.",
          ],
          examImportance: "이 단원이 약하면 정비례와 반비례, 확률 단원까지 연결이 흔들린다.",
          concepts: [
            { term: "비", simple: "두 수를 비교하는 방법", detailed: "순서를 지켜 a:b 꼴로 나타낸다.", exam: "비는 순서를 바꾸면 다른 뜻이 된다." },
            { term: "비율", simple: "비를 분수나 소수로 나타낸 값", detailed: "비교 기준에 대한 상대적인 크기", exam: "비율은 퍼센트와 연결된다." },
            { term: "백분율", simple: "100을 기준으로 한 비율", detailed: "퍼센트 기호로 나타낸 비율", exam: "부분/전체 × 100%" },
            { term: "기준량", simple: "비교의 기준이 되는 양", detailed: "비율 계산에서 나누는 기준 값", exam: "기준량을 잘못 잡으면 오답" },
          ],
        }),
      ],
    },
    {
      id: "middle1",
      name: "중학교 1학년",
      units: [
        createUnit({
          subject: "math",
          grade: "middle1",
          title: "정비례와 반비례",
          field: "함수",
          difficulty: "핵심",
          teaser: "비가 일정한 관계와 곱이 일정한 관계를 식, 표, 그래프로 묶어 이해하는 단원입니다.",
          achievementGoals: [
            "정비례와 반비례의 뜻을 식, 표, 그래프로 연결해 설명할 수 있다.",
            "정비례식 y=ax와 반비례식 y=a/x를 해석할 수 있다.",
            "실생활 상황이 정비례인지 반비례인지 판단하고 근거를 말할 수 있다.",
          ],
          examImportance: "표나 그래프만 보고도 정비례·반비례를 가려야 하고, 일차함수와 헷갈리는 함정 보기까지 자주 출제된다.",
          coreConcepts: [
            { term: "정비례", simple: "한 양이 몇 배가 되면 다른 양도 같은 배가 되는 관계", detailed: "대응하는 두 양의 비가 일정할 때 정비례라고 하며 식으로 y=ax로 나타낸다.", exam: "정비례는 y=ax 꼴이며 그래프가 원점을 지나는 직선이다." },
            { term: "반비례", simple: "한 양이 커질수록 다른 양이 반대로 작아지는 관계", detailed: "두 양의 곱이 일정할 때 반비례라고 하며 식으로 y=a/x로 나타낸다.", exam: "반비례는 xy=a가 일정하며 그래프는 좌표축에 가까워지는 두 갈래 곡선이다." },
            { term: "비례상수", simple: "관계를 결정하는 일정한 수", detailed: "정비례에서는 y/x의 값, 반비례에서는 xy의 값이 비례상수 역할을 한다.", exam: "비례상수는 식의 모양과 그래프 기울기, 위치를 결정한다." },
            { term: "표-식-그래프 연결", simple: "같은 관계를 여러 방식으로 표현하는 것", detailed: "표에서 비나 곱을 확인하고, 식으로 정리한 뒤 그래프 모양과 원점 통과 여부를 점검한다.", exam: "표만 보고도 정비례·반비례를 판정하는 문제가 잦다." },
          ],
          principles: [
            { title: "왜 정비례는 y=ax 꼴인가", body: "정비례에서는 y/x가 항상 일정하다. 그 일정한 값을 a라고 놓으면 y/x=a, 양변에 x를 곱해 y=ax가 된다. 즉 식은 개념을 간단히 적어 놓은 결과이다." },
            { title: "왜 반비례는 y=a/x 꼴인가", body: "반비례에서는 xy가 일정하므로 그 일정한 값을 a라고 두면 xy=a가 된다. y를 나타내기 위해 x로 나누면 y=a/x가 된다." },
            { title: "그래프 해석의 핵심", body: "정비례 그래프는 비례상수의 부호에 따라 오르내리는 원점 통과 직선이 되고, 반비례 그래프는 1사분면과 3사분면 또는 2사분면과 4사분면에 놓이는 곡선으로 나타난다." },
            { title: "시험에서 실수하는 지점", body: "표를 보고 무조건 직선이면 정비례라고 생각하거나, 정비례와 일차함수 차이를 놓치는 경우가 많다. 원점을 지나는지와 상수항 존재를 꼭 확인해야 한다." },
          ],
          formulas: [
            { name: "정비례식", formula: "y = ax", meaning: "a는 비례상수, 그래프는 원점을 지나는 직선" },
            { name: "반비례식", formula: "y = a/x", meaning: "또는 xy=a, 곱이 일정한 관계를 나타낸다." },
          ],
          keyTerms: [
            { term: "비례상수", meaning: "관계의 세기를 결정하는 일정한 수" },
            { term: "원점", meaning: "좌표평면에서 (0, 0)에 해당하는 점" },
            { term: "쌍곡선", meaning: "반비례 그래프처럼 축에 가까워지는 곡선 모양" },
          ],
          mustMemorize: [
            "정비례는 비가 일정, 반비례는 곱이 일정하다.",
            "정비례식은 y=ax, 반비례식은 y=a/x이다.",
            "정비례 그래프는 원점을 지나고, 반비례 그래프는 원점을 지나지 않는다.",
            "정비례와 일차함수는 상수항 유무로 구분한다.",
          ],
          commonMistakes: [
            "정비례를 y=ax+b 꼴과 구분하지 못하는 실수",
            "반비례에서 비가 일정하다고 생각하는 실수",
            "그래프 모양만 보고 사분면 위치를 확인하지 않는 실수",
          ],
          examTips: [
            "표가 주어지면 먼저 y/x와 xy를 각각 계산해 본다.",
            "정비례 그래프는 원점 통과 여부가 핵심 단서다.",
            "실생활 상황 문제는 한 양이 몇 배일 때 다른 양이 어떻게 변하는지 문장으로 먼저 생각한다.",
            "서술형에서는 '비가 일정하다', '곱이 일정하다'를 정확히 써야 한다.",
          ],
          examples: [
            { kind: "실생활 예시", title: "속력이 일정할 때 거리와 시간", body: "속력이 일정하면 거리는 시간에 정비례한다." },
            { kind: "실생활 예시", title: "일정한 거리를 갈 때 속력과 시간", body: "거리가 일정하면 속력이 커질수록 시간은 줄어 반비례 관계가 된다." },
            { kind: "교과서형 예시", title: "표에서 관계 찾기", body: "대응값의 비를 확인해 정비례인지, 곱을 확인해 반비례인지 판정한다." },
            { kind: "시험형 예시", title: "일차함수와 비교", body: "y=2x+3은 정비례가 아니라는 점을 묻는 함정 문제가 자주 나온다." },
          ],
          relatedFigures: [
            { name: "데카르트", work: "좌표를 사용해 수와 도형 관계를 연결하는 해석기하의 기초를 놓았다." },
          ],
          flashcards: [
            { front: "정비례", back: "비가 일정 / y=ax / 원점 지나는 직선" },
            { front: "반비례", back: "곱이 일정 / y=a/x / 두 갈래 곡선" },
            { front: "비례상수", back: "정비례는 y/x, 반비례는 xy로 해석 가능" },
            { front: "함정 포인트", back: "y=ax+b는 정비례가 아니다" },
          ],
          questions: proportionalQuestions,
          summary: {
            tenLines: [
              "정비례는 비가 일정하다.",
              "반비례는 곱이 일정하다.",
              "정비례식은 y=ax이다.",
              "반비례식은 y=a/x이다.",
              "정비례 그래프는 원점을 지난다.",
              "반비례 그래프는 두 갈래 곡선이다.",
              "비례상수는 관계를 결정한다.",
              "표에서는 비와 곱을 계산해 판정한다.",
              "실생활 상황을 문장으로 먼저 해석한다.",
              "정비례와 일차함수는 상수항 유무로 구별한다.",
            ],
            table: [
              { label: "정비례", value: "비 일정 / y=ax / 원점 지나는 직선" },
              { label: "반비례", value: "곱 일정 / y=a/x / 쌍곡선" },
              { label: "판단법", value: "표에서는 비와 곱 확인" },
            ],
            oneMinute: "정비례는 비, 반비례는 곱이라는 기준부터 떠올리자. 식으로 옮길 때는 y=ax와 y=a/x를 구분하고, 그래프에서는 원점 통과 여부와 곡선 모양을 확인하면 된다.",
            blanks: [
              "정비례는 ______가 일정하다.",
              "반비례는 ______이(가) 일정하다.",
              "정비례식: y = ______",
              "반비례식: y = ______",
            ],
          },
        }),
        createUnit({
          subject: "math",
          grade: "middle1",
          title: "좌표평면과 그래프",
          field: "함수",
          difficulty: "핵심",
          teaser: "순서쌍 읽기부터 축, 사분면, 그래프 해석까지 좌표평면의 기본을 탄탄히 다지는 단원입니다.",
          achievementGoals: [
            "좌표평면에서 점의 위치를 순서쌍으로 나타낼 수 있다.",
            "사분면의 뜻과 각 점의 부호를 구분할 수 있다.",
            "표, 식, 그래프를 서로 바꾸어 읽고 해석할 수 있다.",
          ],
          examImportance: "순서쌍 순서를 바꾸는 실수, 사분면 부호 실수, 그래프 해석 문제는 중학교 수학 전 범위에 계속 이어지는 기본 실수 포인트다.",
          coreConcepts: [
            { term: "좌표평면", simple: "x축과 y축으로 이루어진 평면", detailed: "가로축 x축과 세로축 y축이 만나 위치를 수로 표현하는 기준을 만든다.", exam: "x좌표를 먼저, y좌표를 나중에 쓰는 순서쌍 체계를 사용한다." },
            { term: "순서쌍", simple: "점의 위치를 나타내는 두 수", detailed: "(x, y) 꼴로 나타내며 괄호 안 첫 번째 수는 x좌표, 두 번째 수는 y좌표이다.", exam: "순서가 바뀌면 완전히 다른 점이 된다." },
            { term: "사분면", simple: "좌표축이 나누는 네 영역", detailed: "제1사분면부터 반시계 방향으로 번호를 붙이고, 각 사분면에서 x와 y 부호가 달라진다.", exam: "1사분면 (+,+), 2사분면 (-,+), 3사분면 (-,-), 4사분면 (+,-)" },
            { term: "그래프 해석", simple: "그래프에서 관계를 읽는 것", detailed: "축의 이름, 단위, 증가와 감소, 절편, 교점 등을 보고 양의 관계를 해석한다.", exam: "문제를 읽기 전에 축과 단위를 먼저 확인한다." },
          ],
          principles: [
            { title: "순서쌍은 왜 순서가 중요한가", body: "좌표평면에서는 먼저 x축 방향, 그다음 y축 방향으로 이동하기 때문에 (2, 3)과 (3, 2)는 다른 점이다." },
            { title: "사분면 부호를 묶어 외우는 법", body: "1사분면에서 시작해 반시계 방향으로 x 또는 y 부호가 하나씩 바뀐다고 보면 빠르게 기억할 수 있다." },
            { title: "그래프 해석이 중요한 이유", body: "좌표평면은 단독 단원으로 끝나지 않는다. 정비례, 일차함수, 통계 그래프까지 모두 좌표 읽기 능력을 바탕으로 이어진다." },
          ],
          formulas: [],
          keyTerms: [
            { term: "원점", meaning: "x축과 y축이 만나는 점 (0, 0)" },
            { term: "x좌표", meaning: "가로 방향 위치를 나타내는 수" },
            { term: "y좌표", meaning: "세로 방향 위치를 나타내는 수" },
          ],
          mustMemorize: [
            "순서쌍은 (x, y) 순서로 쓴다.",
            "원점 좌표는 (0, 0)이다.",
            "1사분면부터 4사분면까지의 부호를 외운다.",
            "그래프를 읽을 때는 축 이름과 단위를 먼저 본다.",
          ],
          commonMistakes: [
            "(x, y)를 (y, x)로 바꾸어 읽는 실수",
            "사분면 번호 방향을 거꾸로 외우는 실수",
            "축 단위를 무시하고 그래프를 해석하는 실수",
          ],
          examTips: [
            "점이 축 위에 있으면 사분면이 아니라 축 위 점임을 분명히 쓴다.",
            "표를 그래프로 옮길 때는 모든 점을 정확히 찍고 순서대로 연결 여부를 확인한다.",
            "문장형 그래프 해석에서는 증가, 감소, 일정 구간을 나누어 말한다.",
          ],
          examples: [
            { kind: "실생활 예시", title: "지도 좌표", body: "격자 지도에서 위치를 순서쌍으로 나타내는 방식은 좌표평면 개념과 연결된다." },
            { kind: "교과서형 예시", title: "점 찍기", body: "(−2, 3), (4, −1)처럼 각 사분면 점을 직접 찍는 문제가 기본이다." },
            { kind: "시험형 예시", title: "그래프 해석", body: "시간과 거리 그래프를 보고 어느 구간에서 빠르게 이동했는지 해석하는 문제가 나온다." },
          ],
          relatedFigures: [
            { name: "데카르트", work: "좌표평면 도입으로 수와 도형 문제를 하나의 언어로 표현할 수 있게 했다." },
          ],
          flashcards: [
            { front: "순서쌍", back: "(x, y) / x 먼저, y 나중" },
            { front: "원점", back: "(0, 0) / 두 축의 만나는 점" },
            { front: "제2사분면", back: "x 음수, y 양수" },
            { front: "그래프 해석", back: "축 이름, 단위, 증가·감소 먼저 보기" },
          ],
          questions: createMiniUnit({
            subject: "math",
            grade: "middle1",
            title: "좌표평면과 그래프",
            field: "함수",
            difficulty: "핵심",
            teaser: "",
            achievementGoals: [],
            examImportance: "",
            concepts: [
              { term: "좌표평면", simple: "x축과 y축으로 이루어진 평면", detailed: "위치를 수로 표현하는 평면", exam: "점 위치를 수로 읽는 기준" },
              { term: "순서쌍", simple: "(x, y) 꼴", detailed: "x 먼저, y 나중", exam: "순서가 중요하다" },
              { term: "원점", simple: "(0, 0)", detailed: "두 축의 교점", exam: "좌표 출발점" },
              { term: "사분면", simple: "네 영역", detailed: "부호에 따라 구분", exam: "1사분면부터 4사분면까지 부호 기억" },
              { term: "그래프 해석", simple: "그래프에서 관계 읽기", detailed: "축과 단위를 먼저 본다", exam: "증가·감소·일정 구간 해석" },
            ],
          }).questions,
          summary: {
            tenLines: [
              "좌표평면은 x축과 y축으로 이루어진다.",
              "원점은 (0, 0)이다.",
              "순서쌍은 x를 먼저 쓴다.",
              "순서쌍 순서가 바뀌면 다른 점이다.",
              "좌표축은 평면을 네 사분면으로 나눈다.",
              "1사분면은 x와 y가 모두 양수다.",
              "2사분면은 x 음수, y 양수다.",
              "3사분면은 둘 다 음수다.",
              "4사분면은 x 양수, y 음수다.",
              "그래프 해석은 축과 단위 확인부터 한다.",
            ],
            table: [
              { label: "원점", value: "(0, 0)" },
              { label: "제1사분면", value: "(+, +)" },
              { label: "제2사분면", value: "(-, +)" },
              { label: "제3사분면", value: "(-, -)" },
              { label: "제4사분면", value: "(+, -)" },
            ],
            oneMinute: "좌표는 x부터 읽고, 점이 어느 사분면에 있는지 부호로 판단하자. 그래프 문제는 축 이름과 단위를 확인한 뒤 관계를 해석한다.",
            blanks: [
              "순서쌍은 (______, ______) 순서로 쓴다.",
              "원점 좌표는 (______, ______)이다.",
              "제3사분면의 부호는 (______, ______)이다.",
            ],
          },
        }),
      ],
    },
    {
      id: "middle2",
      name: "중학교 2학년",
      units: [
        createMiniUnit({
          subject: "math",
          grade: "middle2",
          title: "일차함수",
          field: "함수",
          difficulty: "응용",
          teaser: "기울기와 y절편을 중심으로 표, 식, 그래프를 연결하는 핵심 단원입니다.",
          achievementGoals: [
            "일차함수 식을 읽을 수 있다.",
            "기울기와 y절편을 해석할 수 있다.",
            "그래프에서 두 점 사이 변화량을 해석할 수 있다.",
          ],
          examImportance: "정비례 뒤에 이어지는 심화 단원으로 그래프 해석 비중이 크다.",
          concepts: [
            { term: "기울기", simple: "가파른 정도", detailed: "x가 1 늘 때 y가 얼마나 변하는지", exam: "변화율로 해석" },
            { term: "y절편", simple: "y축과 만나는 값", detailed: "x=0일 때의 y값", exam: "그래프 시작점 해석" },
            { term: "일차함수", simple: "y=ax+b 꼴 함수", detailed: "직선 그래프로 나타나는 함수", exam: "정비례는 b=0인 특별한 경우" },
            { term: "변화율", simple: "변하는 비율", detailed: "두 양의 변화를 비교하는 값", exam: "기울기와 연결" },
          ],
        }),
      ],
    },
    {
      id: "middle3",
      name: "중학교 3학년",
      units: [
        createMiniUnit({
          subject: "math",
          grade: "middle3",
          title: "이차함수 기초",
          field: "함수",
          difficulty: "심화",
          teaser: "포물선의 모양, 꼭짓점, 축, 최대·최소를 읽는 중3 핵심 단원입니다.",
          achievementGoals: [
            "이차함수 그래프의 기본 모양을 설명할 수 있다.",
            "꼭짓점과 축의 의미를 말할 수 있다.",
            "그래프를 보고 최대값과 최소값을 판단할 수 있다.",
          ],
          examImportance: "고등 함수 학습으로 넘어가기 전 그래프 해석 감각을 키우는 핵심 단원이다.",
          concepts: [
            { term: "포물선", simple: "이차함수 그래프 모양", detailed: "위로 열리거나 아래로 열리는 곡선", exam: "계수 부호에 따라 방향 결정" },
            { term: "꼭짓점", simple: "그래프의 가장 높은 점 또는 낮은 점", detailed: "이차함수의 최대·최소와 연결되는 점", exam: "좌표를 읽는 문제 출제" },
            { term: "축", simple: "그래프를 반으로 가르는 직선", detailed: "꼭짓점을 지나며 좌우 대칭 기준이 되는 직선", exam: "대칭성과 연결" },
            { term: "최대·최소", simple: "가장 큰 값과 가장 작은 값", detailed: "그래프 방향과 꼭짓점 위치로 판단", exam: "함수값과 혼동 금지" },
          ],
        }),
      ],
    },
    {
      id: "highCommon",
      name: "고등 공통/기초",
      units: [
        createMiniUnit({
          subject: "math",
          grade: "highCommon",
          title: "공통수학: 다항식과 방정식",
          field: "공통수학",
          difficulty: "고등 핵심",
          teaser: "2029 대입 세대 공통수학 흐름에 맞춰 다항식 계산, 나머지정리, 인수정리, 방정식 해석을 정리합니다.",
          achievementGoals: [
            "다항식의 계산 원리를 설명할 수 있다.",
            "나머지정리와 인수정리를 식 변형과 연결할 수 있다.",
            "방정식을 해석하고 의미를 그래프와 연결할 수 있다.",
          ],
          examImportance: "고등 공통수학의 첫 관문이라 계산 정확도와 개념 이해가 모두 필요하다.",
          concepts: [
            { term: "다항식", simple: "여러 항의 합으로 이루어진 식", detailed: "계수와 차수를 기준으로 정리하며 계산 규칙이 중요하다.", exam: "항과 차수 구조를 정확히 읽는다." },
            { term: "나머지정리", simple: "x-a로 나눌 때의 나머지", detailed: "다항식 f(x)를 x-a로 나눈 나머지는 f(a)와 같다.", exam: "대입과 식 계산을 연결하는 핵심 정리" },
            { term: "인수정리", simple: "나머지가 0이면 인수", detailed: "f(a)=0이면 x-a는 f(x)의 인수이다.", exam: "방정식의 근과 인수 연결" },
            { term: "방정식의 근", simple: "식을 참으로 만드는 값", detailed: "그래프와 연결하면 x축과 만나는 점의 x좌표로 이해할 수 있다.", exam: "대수와 그래프 해석 연결" },
          ],
        }),
        createMiniUnit({
          subject: "math",
          grade: "highCommon",
          title: "공통수학: 함수와 그래프",
          field: "공통수학",
          difficulty: "고등 핵심",
          teaser: "함수의 뜻, 여러 표현 방식, 그래프 이동과 해석을 공통수학 수준으로 정리합니다.",
          achievementGoals: [
            "함수의 뜻과 대응 관계를 설명할 수 있다.",
            "그래프 이동과 식의 변화를 연결할 수 있다.",
            "함수 그래프를 보고 성질을 해석할 수 있다.",
          ],
          examImportance: "후속 단원 전체의 언어가 되는 개념이어서 용어와 해석을 정확히 잡아야 한다.",
          concepts: [
            { term: "함수", simple: "입력값마다 출력값이 하나씩 정해지는 관계", detailed: "정의역과 공역, 대응 규칙을 함께 봐야 한다.", exam: "한 입력에 출력 하나" },
            { term: "정의역", simple: "입력값의 모임", detailed: "함수에 넣을 수 있는 x값의 범위", exam: "제한 조건과 함께 읽기" },
            { term: "그래프 이동", simple: "그래프 위치가 바뀌는 것", detailed: "식의 상수 변화가 그래프를 위아래, 좌우로 움직인다.", exam: "식 변화와 그래프 변화 연결" },
            { term: "증가와 감소", simple: "x가 커질 때 y가 어떻게 변하는지", detailed: "구간별 성질을 읽어 함수 해석 문제에 적용한다.", exam: "구간 성질 서술" },
          ],
        }),
        createMiniUnit({
          subject: "math",
          grade: "highCommon",
          title: "공통수학: 경우의 수와 확률 기초",
          field: "공통수학",
          difficulty: "고등 확장",
          teaser: "경우의 수, 순열, 조합, 확률의 기본 구조를 공통 과목 흐름으로 정리합니다.",
          achievementGoals: [
            "곱의 법칙과 합의 법칙을 구분할 수 있다.",
            "순열과 조합의 기본 의미를 설명할 수 있다.",
            "확률을 경우의 수와 연결해 계산할 수 있다.",
          ],
          examImportance: "조건 정리 실수가 많아 표와 나무그림을 그리는 습관이 중요하다.",
          concepts: [
            { term: "곱의 법칙", simple: "차례대로 선택하는 경우", detailed: "단계별 선택 수를 곱해 전체 경우의 수를 구한다.", exam: "독립된 단계별 선택" },
            { term: "합의 법칙", simple: "서로 겹치지 않는 경우 더하기", detailed: "동시에 일어날 수 없는 경우들을 더한다.", exam: "겹침 여부 먼저 확인" },
            { term: "순열", simple: "순서가 있는 배열", detailed: "배열 순서가 달라지면 다른 경우로 본다.", exam: "순서 중요" },
            { term: "조합", simple: "순서가 없는 선택", detailed: "구성원만 같으면 같은 경우로 본다.", exam: "순서 무시" },
          ],
        }),
      ],
    },
  ],
};

export default math;
